from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import re

from loguru import logger

from dsbx.Gen import InputModel
from dsbx.Sim.Events import (
    ArrivalEvent,
    DueDateEvent,
    BreakdownEvent,
    PriorityChangeEvent,
    OrderCancellationEvent,
    MachineRepairCompletionEvent,
    ProcessTimeChangeEvent,
    PreventiveMaintenanceEvent,
    RouteChangeEvent,
    DueDateChangeEvent,
    Event,
)
from dsbx.Sim.State import (
    SystemState,
    JobState,
    MachineState,
    OperationState,
    ScheduleSegment,
)
from dsbx.Sim.Snapshot import (
    Snapshot,
    JobSnapshot,
    JobOpSnapshot,
    MachineSnapshot,
    MachineScheduleSegmentSnapshot,
    EventSnapshot,
    SystemStats,
    StabilityStats,
)


class DynaSchedSim:
    """Core simulator for dynamic scheduling instances.

    The simulator consumes event streams generated by
    :mod:`dsbx.Gen`, maintains explicit job and machine state, and
    exposes rich snapshots at decision points.

    The implementation follows the same time-advance style as the legacy
    LLM scheduling environment: ``time`` is the decision reference time,
    job and machine availability controls when the next operation can start,
    dynamic events become active when the clock reaches their timestamp, and
    snapshots keep planned start/end times for optimization and visualization.
    """

    def __init__(self, model: InputModel, events: List[Event]):
        self.model = model
        # Events are assumed to be fully generated; sort by (time, priority)
        # to obtain deterministic semantics for simultaneous events.
        self._events: List[Event] = sorted(
            events, key=lambda e: (float(e.time), getattr(e, "priority", 100))
        )
        self._event_index: int = 0

        # Internal state
        self.state: SystemState = self._init_system_state()

        # Downtime blocks; keyed by machine id or group id
        self._block_until_machine: Dict[str, float] = defaultdict(float)
        self._block_until_group: Dict[str, float] = defaultdict(float)

        # For stability metrics and Gantt-like visualization
        self._prev_snapshot: Optional[Snapshot] = None
        self._gantt: List[Dict[str, Any]] = []

        # Aggregated dynamic event counters for mechanism-aware prompts and
        # analysis. These are reset at the beginning of each episode.
        self._event_counters: Dict[str, int] = defaultdict(int)

    # ------------------------------------------------------------------
    # State initialisation helpers
    # ------------------------------------------------------------------
    def _init_system_state(self) -> SystemState:
        horizon = float(self.model.scale.horizon)

        machines: Dict[str, MachineState] = {}
        machine_groups: Dict[str, Dict[str, Any]] = {}

        for m in self.model.plant.machines:
            ms = MachineState(
                machine_id=m.id,
                group=m.group,
                speed=getattr(m, "speed", 1.0),
            )
            machines[m.id] = ms
            mg = machine_groups.setdefault(m.group, {"machine_ids": [], "total_speed": 0.0})
            mg["machine_ids"].append(m.id)
            mg["total_speed"] += getattr(m, "speed", 1.0)

        system = SystemState(
            time=0.0,
            prev_decision_time=0.0,
            horizon=horizon,
            lookahead_horizon=horizon,
            jobs={},
            machines=machines,
            machine_groups=machine_groups,
        )
        return system

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def reset(self) -> Snapshot:
        """Reset internal time/state and return the initial snapshot.

        This does **not** regenerate events; it assumes the caller provides a
        fresh event list when creating a new simulator instance.
        """

        self.state = self._init_system_state()
        self._event_index = 0
        self._block_until_machine.clear()
        self._block_until_group.clear()
        self._gantt.clear()
        self._prev_snapshot = None
        self._event_counters.clear()

        # Process any events at time 0 (e.g., warm-start WIP,
        # initial due dates, etc.).
        self._process_events_until(0.0)
        snap = self.export_snapshot()
        self._prev_snapshot = snap
        return snap

    def step_action(self, action: Dict[str, Any]) -> Snapshot:
        """Apply a single scheduling decision and return the new snapshot.

        Parameters
        ----------
        action:
            A dictionary describing the scheduling decision. By convention,
            it must contain at least:
            - ``job_id`` (str)
            - ``machine_group`` (str)
            It may optionally include:
            - ``machine_id`` (str): specific machine choice within the group.
        """

        # Ensure all events up to the current decision time are applied
        self._process_events_until(self.state.time)

        job_id = str(action["job_id"])
        job = self.state.jobs.get(job_id)
        if job is None:
            raise ValueError(f"Unknown job_id in action: {job_id}")
        if job.status == "cancelled":
            raise ValueError(f"Cannot schedule cancelled job: {job_id}")
        if job.status == "completed":
            raise ValueError(f"Job {job_id} is already completed; no remaining operations can be scheduled")

        k = job.current_op_index
        if k >= job.total_ops:
            raise ValueError(f"Job {job_id} has no remaining operations to schedule")

        op = job.ops[k]
        group = op.machine_group
        requested_mid = action.get("machine_id")
        machine_id = self._select_machine_for_action(job_id, group, requested_mid)
        machine = self.state.machines[machine_id]

        t_now = self.state.time
        job_avail = max(job.release_time, job.next_available_time)
        machine_avail = machine.available_from
        block_until = self._machine_block_until(machine_id, machine.group)

        start = max(t_now, job_avail, machine_avail, block_until)
        # Processing time is adjusted by machine speed
        proc_time = float(op.proc_time_realized) / max(1e-9, machine.speed)

        if machine.schedule_segments:
            latest_end = max(float(seg.end) for seg in machine.schedule_segments)
            if start < latest_end - 1e-9:
                logger.warning(
                    "Adjusting start time on machine %s to avoid overlap: requested=%.6f, latest_end=%.6f",
                    machine_id,
                    start,
                    latest_end,
                )
                start = latest_end

        end = start + proc_time

        # Update operation
        op.prev_start_time = op.start_time
        op.prev_machine_id = machine_id
        op.start_time = start
        op.end_time = end
        op.status = "done"

        # Update job progress and statistics
        job.next_available_time = end

        ops = list(getattr(job, "ops", []))

        new_k = 0
        while (
            new_k < job.total_ops
            and new_k < len(ops)
            and getattr(ops[new_k], "status", None) in ("done", "cancelled")
        ):
            new_k += 1
        job.current_op_index = new_k

        job.remaining_work_content = sum(
            float(getattr(o, "proc_time_realized", 0.0))
            for o in ops
            if getattr(o, "status", None) not in ("done", "cancelled")
        )

        all_done_or_cancelled = bool(ops) and all(
            getattr(o, "status", None) in ("done", "cancelled") for o in ops
        )

        if all_done_or_cancelled:
            job.status = "completed"
            job.completion_time = end
            job.lateness = end - job.due_date
            job.tardiness = max(0.0, job.lateness)
            job.current_op_index = job.total_ops
            job.remaining_work_content = 0.0
        else:
            job.status = "waiting"
            job.completion_time = None
            job.lateness = None
            job.tardiness = None

        # Update machine state
        machine.current_job_id = job_id
        machine.current_op_id = op.op_id
        machine.available_from = max(machine.available_from, end)
        machine.status = "busy"
        machine.schedule_segments.append(
            ScheduleSegment(start=start, end=end, job_id=job_id, op_id=op.op_id, is_frozen=False)
        )
        machine.busy_time += max(0.0, end - start)

        # Record Gantt entry for downstream visualization
        self._gantt.append(
            {
                "job_id": job_id,
                "operation": k,
                "machine_id": machine_id,
                "start_time": float(start),
                "end_time": float(end),
                "status": "completed",
            }
        )

        # Time at decision point does not automatically jump to `end`.
        # We stay at the current decision time; the caller can use
        # `advance_to_next_decision_point` to move time forward.
        self.state.prev_decision_time = self.state.time
        # We consider this a rescheduling step
        self.state.num_reschedules += 1
        self.state.last_schedule_change_time = self.state.time

        self._log_job_invariants("step_action")

        snap = self.export_snapshot()
        self._prev_snapshot = snap
        return snap

    def advance_to_next_decision_point(self) -> Snapshot:
        """Advance simulation time to the next moment where a decision is needed.

        If there are already ready operations at the current time, this is a
        no-op and simply returns the current snapshot.
        """

        if self._get_ready_operations():
            snap = self.export_snapshot()
            self._prev_snapshot = snap
            return snap

        t = self.state.time
        candidates: List[float] = []

        # 1) Next job availability (end of current operation)
        for job in self.state.jobs.values():
            if job.status in ("completed", "cancelled"):
                continue
            if job.current_op_index >= job.total_ops:
                continue
            if job.next_available_time > t:
                candidates.append(job.next_available_time)

        # 2) Next machine availability (end of scheduled work)
        for mach in self.state.machines.values():
            if mach.available_from > t:
                candidates.append(mach.available_from)

        # 3) Downtime blocks
        for v in self._block_until_machine.values():
            if v > t:
                candidates.append(v)
        for v in self._block_until_group.values():
            if v > t:
                candidates.append(v)

        # 4) Next external event time
        if self._event_index < len(self._events):
            candidates.append(float(self._events[self._event_index].time))

        if not candidates:
            # No further evolution; return current snapshot
            try:
                unfinished_jobs = [
                    getattr(job, "job_id", None)
                    for job in self.state.jobs.values()
                    if getattr(job, "status", None) not in ("completed", "cancelled")
                ]
                unfinished_jobs = [jid for jid in unfinished_jobs if jid is not None]

                has_future_events = self._event_index < len(self._events)
                next_event_time = None
                if has_future_events:
                    try:
                        next_event_time = float(self._events[self._event_index].time)
                    except Exception:
                        next_event_time = None

                if unfinished_jobs or has_future_events:
                    try:
                        logger.error(
                            "DynaSchedSim: no candidate future times at t={} (unfinished_jobs={}, "
                            "event_index={} len_events={} next_event_time={})",
                            float(t),
                            ",".join(map(str, unfinished_jobs)) if unfinished_jobs else "",
                            int(self._event_index),
                            int(len(self._events)),
                            next_event_time,
                        )

                        for job in self.state.jobs.values():
                            jid = getattr(job, "job_id", None)
                            status = getattr(job, "status", None)
                            cur_idx = int(getattr(job, "current_op_index", 0))
                            total_ops = int(getattr(job, "total_ops", 0))
                            next_avail = float(getattr(job, "next_available_time", 0.0))
                            release_time = float(getattr(job, "release_time", 0.0))
                            due_date = float(getattr(job, "due_date", 0.0))
                            remaining_work = float(
                                getattr(job, "remaining_work_content", 0.0)
                            )
                            priority = float(getattr(job, "priority", 0.0))

                            ops = list(getattr(job, "ops", []))
                            op_info = None
                            if 0 <= cur_idx < len(ops):
                                op = ops[cur_idx]
                                op_info = {
                                    "index": int(getattr(op, "index", cur_idx)),
                                    "status": getattr(op, "status", None),
                                    "machine_group": getattr(op, "machine_group", None),
                                    "candidate_machines": list(
                                        getattr(op, "candidate_machines", [])
                                    ),
                                }

                            logger.error(
                                "DynaSchedSim debug: job_id={} status={} cur_idx={}/{} "
                                "next_avail={} release={} due={} remain={} prio={} cur_op={}",
                                jid,
                                status,
                                cur_idx,
                                total_ops,
                                next_avail,
                                release_time,
                                due_date,
                                remaining_work,
                                priority,
                                op_info,
                            )

                        for mid, mach in self.state.machines.items():
                            available_from = float(getattr(mach, "available_from", 0.0))
                            group = getattr(mach, "group", None)
                            block_until = float(
                                self._machine_block_until(str(mid), str(group))
                            )
                            logger.error(
                                "DynaSchedSim debug: machine_id={} group={} available_from={} block_until={}",
                                str(mid),
                                group,
                                available_from,
                                block_until,
                            )
                    except Exception:
                        logger.exception(
                            "DynaSchedSim: failed to log no-candidates state at time={}",
                            float(t),
                        )

            except Exception:
                # Logging must be best-effort only; never break the simulator here.
                logger.exception(
                    "DynaSchedSim: unexpected error while inspecting no-candidates state at time={}",
                    float(t),
                )

            snap = self.export_snapshot()
            self._prev_snapshot = snap
            return snap

        new_t = min(candidates)
        self._process_events_until(new_t)
        self.state.prev_decision_time = t

        snap = self.export_snapshot()
        self._prev_snapshot = snap
        return snap

    def _log_job_invariants(self, context: str) -> None:
        try:
            eps = 1e-6
            for job in self.state.jobs.values():
                jid = getattr(job, "job_id", None)
                status = getattr(job, "status", None)
                total_ops = int(getattr(job, "total_ops", 0))
                cur_idx = int(getattr(job, "current_op_index", 0))
                remaining = float(getattr(job, "remaining_work_content", 0.0))
                ops = list(getattr(job, "ops", []))

                if 0 <= cur_idx < total_ops and 0 <= cur_idx < len(ops):
                    op = ops[cur_idx]
                    op_status = getattr(op, "status", None)
                    if op_status in ("done", "cancelled"):
                        logger.error(
                            "DynaSchedSim invariant violation after {}: job_id={} current_op_index={}/{} "
                            "points to op status={}",
                            context,
                            jid,
                            cur_idx,
                            total_ops,
                            op_status,
                        )

                if total_ops > 0 and ops:
                    all_done_or_cancelled = all(
                        getattr(op, "status", None) in ("done", "cancelled") for op in ops
                    )
                    if all_done_or_cancelled:
                        if status not in ("completed", "cancelled") or abs(remaining) > eps:
                            logger.error(
                                "DynaSchedSim invariant violation after {}: job_id={} all ops done/cancelled "
                                "but status={} remaining={} cur_idx={}/{}",
                                context,
                                jid,
                                status,
                                remaining,
                                cur_idx,
                                total_ops,
                            )
        except Exception:
            logger.exception(
                "DynaSchedSim: error while checking job invariants after {}",
                context,
            )

    def export_light_state(self) -> Dict[str, Any]:
        self._process_events_until(self.state.time)

        state = self.state

        jobs_dict: Dict[str, Any] = {}
        for jid, job in state.jobs.items():
            ops_info: List[Dict[str, Any]] = []
            for op in job.ops:
                ops_info.append(
                    {
                        "index": int(op.index),
                        "machine_group": op.machine_group,
                        "proc_time_nominal": float(op.proc_time_nominal),
                        "proc_time_realized": float(op.proc_time_realized),
                    }
                )
            jobs_dict[str(jid)] = {
                "release_time": float(job.release_time),
                "due_date": float(job.due_date),
                "total_ops": int(job.total_ops),
                "total_work_content": float(job.total_work_content),
                "remaining_work_content": float(job.remaining_work_content),
                "priority": float(getattr(job, "priority", 0.0)),
                "ops": ops_info,
                "current_op_index": int(getattr(job, "current_op_index", 0)),
            }

        machines_dict: Dict[str, Any] = {}
        for mid, mach in state.machines.items():
            busy_time = 0.0
            for seg in mach.schedule_segments:
                busy_time += float(seg.end - seg.start)
            machines_dict[str(mid)] = {
                "available_from": float(mach.available_from),
                "speed": float(getattr(mach, "speed", 1.0)),
                "busy_time": float(busy_time),
            }

        return {
            "time": float(state.time),
            "jobs": jobs_dict,
            "machines": machines_dict,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _candidate_machines_for_group(self, group: str) -> List[str]:
        # Prefer explicit mapping from machine_groups if available
        mg = self.state.machine_groups.get(group)
        if mg and isinstance(mg.get("machine_ids"), list):
            mids = [str(m) for m in mg["machine_ids"]]
            if mids:
                return mids
        # Fallback: scan machines by group
        mids = [m.machine_id for m in self.state.machines.values() if m.group == group]
        if mids:
            return mids
        # Final fallback: treat group name as pseudo-machine id
        return [group]

    def _select_machine_for_action(
        self,
        job_id: str,
        group: str,
        machine_id_opt: Optional[str],
    ) -> str:
        candidates = self._candidate_machines_for_group(group)
        if machine_id_opt and machine_id_opt in candidates:
            return machine_id_opt

        # Choose the machine that can start the earliest
        t_now = self.state.time
        job = self.state.jobs[job_id]
        k = job.current_op_index
        op = job.ops[k]
        best_mid = candidates[0]
        best_start = float("inf")
        for mid in candidates:
            mach = self.state.machines[mid]
            job_avail = max(job.release_time, job.next_available_time)
            block_until = self._machine_block_until(mid, mach.group)
            start = max(t_now, job_avail, mach.available_from, block_until)
            if start < best_start:
                best_start = start
                best_mid = mid
        return best_mid

    def _machine_block_until(self, mid: str, group: str) -> float:
        return max(self._block_until_machine.get(mid, 0.0), self._block_until_group.get(group, 0.0))

    # ------------------------------------------------------------------
    # Action scoring helpers (LLMEnv-compatible)
    # ------------------------------------------------------------------
    def estimate_action_score(self, action: Dict[str, Any]) -> float:
        """Estimate the quality of an action based on its immediate end time.

        The logic matches ``LLMEnv.estimate_action_score``: estimate the
        completion time of the action on the selected machine, return the
        negative end time so earlier is better, and add a small priority
        correction.
        """

        job_id = str(action["job_id"])
        group = str(action.get("machine_group"))
        requested_mid = action.get("machine_id")

        job = self.state.jobs.get(job_id)
        if job is None or job.current_op_index >= job.total_ops:
            return 0.0

        k = job.current_op_index
        op = job.ops[k]
        machine_id = self._select_machine_for_action(job_id, group, requested_mid)
        mach = self.state.machines[machine_id]

        t_now = self.state.time
        job_avail = max(job.release_time, job.next_available_time)
        block_until = self._machine_block_until(machine_id, mach.group)
        start = max(t_now, job_avail, mach.available_from, block_until)

        pt = float(op.proc_time_realized) / max(1e-9, mach.speed)
        end = start + pt
        pr = float(job.priority)
        return -float(end) + 1e-3 * pr

    def quick_rollout_score(self, action: Dict[str, Any], steps: int = 1) -> float:
        """Approximate makespan impact of an action via a short, greedy rollout.

        The behavior matches ``LLMEnv.quick_rollout_score``: execute the action
        on a lightweight local copy, greedily schedule several subsequent ready
        operations, and return the negative estimated completion time without
        modifying the main simulator state.
        """

        # Local copies of minimal state
        t_now = float(self.state.time)
        tmp_job_prog: Dict[str, int] = {jid: j.current_op_index for jid, j in self.state.jobs.items()}
        tmp_job_avail: Dict[str, float] = {jid: float(j.next_available_time) for jid, j in self.state.jobs.items()}
        tmp_m_avail: Dict[str, float] = {mid: float(m.available_from) for mid, m in self.state.machines.items()}
        tmp_block_m: Dict[str, float] = dict(self._block_until_machine)
        tmp_block_g: Dict[str, float] = dict(self._block_until_group)

        def _ready_ops_local() -> List[Tuple[str, int, str, float]]:
            out: List[Tuple[str, int, str, float]] = []
            for jid, job in self.state.jobs.items():
                k = tmp_job_prog[jid]
                if k >= job.total_ops:
                    continue
                if job.status == "cancelled":
                    continue
                if job.release_time > t_now:
                    continue
                if tmp_job_avail[jid] > t_now:
                    continue
                op = job.ops[k]
                if op.status in ("cancelled", "done"):
                    continue
                out.append((jid, k, op.machine_group, float(op.proc_time_realized)))
            return out

        def _local_block_until(mid: str, group: str) -> float:
            return max(tmp_block_m.get(mid, 0.0), tmp_block_g.get(group, 0.0))

        def _schedule_local(jid: str, group: str) -> float:
            nonlocal t_now
            job = self.state.jobs[jid]
            k = tmp_job_prog[jid]
            if k >= job.total_ops:
                return t_now
            op = job.ops[k]
            pt_real = float(op.proc_time_realized)

            # choose machine
            best_mid = None
            best_start = float("inf")
            for cand in self._candidate_machines_for_group(group):
                mach = self.state.machines[cand]
                job_avail = max(job.release_time, tmp_job_avail[jid])
                block_until = _local_block_until(cand, mach.group)
                start = max(t_now, job_avail, tmp_m_avail.get(cand, 0.0), block_until)
                if start < best_start:
                    best_start = start
                    best_mid = cand

            if best_mid is None:
                return t_now

            mach = self.state.machines[best_mid]
            start = best_start
            pt = pt_real / max(1e-9, mach.speed)
            end = start + pt

            tmp_m_avail[best_mid] = end
            tmp_job_avail[jid] = end
            tmp_job_prog[jid] = k + 1
            t_now = max(t_now, start)
            return end

        # 1) apply the proposed action first
        jid0 = str(action.get("job_id")) if "job_id" in action else None
        if jid0 is not None:
            group0 = str(action.get("machine_group"))
            _schedule_local(jid0, group0)

        # 2) greedy rollout for remaining steps
        s = 1
        max_steps = max(1, int(steps))
        while s < max_steps:
            ready = _ready_ops_local()
            if not ready:
                # advance time to next availability
                next_times: List[float] = []
                for jid, job in self.state.jobs.items():
                    k = tmp_job_prog[jid]
                    if k < job.total_ops and tmp_job_avail[jid] > t_now:
                        next_times.append(tmp_job_avail[jid])
                next_times.extend([v for v in tmp_m_avail.values() if v > t_now])
                next_times.extend([v for v in tmp_block_m.values() if v > t_now])
                next_times.extend([v for v in tmp_block_g.values() if v > t_now])
                if not next_times:
                    break
                t_now = min(next_times)
                continue

            # choose (job, group) with minimal estimated completion time
            best_pair: Optional[Tuple[str, str]] = None
            best_est_end = float("inf")
            for jid, k, group, ptime in ready:
                job = self.state.jobs[jid]
                op = job.ops[k]
                pt_real = float(op.proc_time_realized)
                local_best = float("inf")
                for cand in self._candidate_machines_for_group(group):
                    mach = self.state.machines[cand]
                    job_avail = max(job.release_time, tmp_job_avail[jid])
                    block_until = _local_block_until(cand, mach.group)
                    start = max(t_now, job_avail, tmp_m_avail.get(cand, 0.0), block_until)
                    end = start + pt_real / max(1e-9, mach.speed)
                    if end < local_best:
                        local_best = end
                if local_best < best_est_end:
                    best_est_end = local_best
                    best_pair = (jid, group)

            if best_pair is None:
                break
            _schedule_local(best_pair[0], best_pair[1])
            s += 1

        # Estimated makespan/finish time
        est_finish = max(list(tmp_m_avail.values()) + [t_now]) if tmp_m_avail else t_now
        return -float(est_finish)

    # ------------------------------------------------------------------
    # Event processing
    # ------------------------------------------------------------------
    def _process_events_until(self, t: float) -> None:
        """Apply all events with time <= t in chronological order."""

        n = len(self._events)
        while self._event_index < n and float(self._events[self._event_index].time) <= t:
            ev = self._events[self._event_index]
            et = float(ev.time)

            if isinstance(ev, ArrivalEvent):
                self._event_counters["arrival"] += 1
                self._handle_arrival(ev, et)
            elif isinstance(ev, DueDateEvent):
                self._event_counters["due_date"] += 1
                self._handle_due_date(ev, et)
            elif isinstance(ev, BreakdownEvent):
                self._event_counters["breakdown"] += 1
                self._handle_breakdown(ev, et)
            elif isinstance(ev, MachineRepairCompletionEvent):
                self._event_counters["repair"] += 1
                self._handle_repair_completion(ev, et)
            elif isinstance(ev, ProcessTimeChangeEvent):
                self._event_counters["ptime_change"] += 1
                self._handle_ptime_change(ev, et)
            elif isinstance(ev, PriorityChangeEvent):
                self._event_counters["priority_change"] += 1
                self._handle_priority_change(ev, et)
            elif isinstance(ev, OrderCancellationEvent):
                self._event_counters["cancellation"] += 1
                self._handle_cancellation(ev, et)
            elif isinstance(ev, RouteChangeEvent):
                self._event_counters["route_change"] += 1
                self._handle_route_change(ev, et)
            elif isinstance(ev, DueDateChangeEvent):
                self._event_counters["due_date_change"] += 1
                self._handle_due_date_change(ev, et)
            elif isinstance(ev, PreventiveMaintenanceEvent):
                self._event_counters["pm"] += 1
                self._handle_pm(ev, et)
            else:  # pragma: no cover - defensive
                logger.warning(f"Unhandled event type: {getattr(ev, 'event_type', type(ev))}")

            self._log_job_invariants(
                f"process_events_until:{getattr(ev, 'event_type', type(ev))}"
            )

            self._event_index += 1

        self.state.time = max(self.state.time, t)

    # --- Individual event handlers ------------------------------------
    def _handle_arrival(self, ev: ArrivalEvent, t: float) -> None:
        if ev.job_id in self.state.jobs:
            logger.warning(f"Duplicate ArrivalEvent for job_id={ev.job_id}")
            return

        # Build operations from routing + process times
        ops: List[OperationState] = []
        total_work = 0.0
        for idx, (group, pt) in enumerate(zip(ev.routing, ev.process_times)):
            pt_val = float(pt)
            total_work += pt_val
            op_id = f"{ev.job_id}-op{idx}"
            ops.append(
                OperationState(
                    op_id=op_id,
                    job_id=ev.job_id,
                    index=idx,
                    machine_group=group,
                    candidate_machines=self._candidate_machines_for_group(group),
                    proc_time_nominal=pt_val,
                    proc_time_realized=pt_val,
                    status="waiting" if idx == 0 else "not_released",
                )
            )

        horizon = float(self.state.horizon)

        job = JobState(
            job_id=ev.job_id,
            family=ev.job_family,
            release_time=float(t),
            due_date=horizon,  # will be updated by DueDateEvent
            initial_due_date=horizon,
            status="waiting",
            current_op_index=0,
            total_ops=len(ops),
            total_work_content=total_work,
            remaining_work_content=total_work,
            next_available_time=float(t),
            ops=ops,
        )
        self.state.jobs[ev.job_id] = job

    def _handle_due_date(self, ev: DueDateEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"DueDateEvent for unknown job_id={ev.job_id}")
            return
        new_due = float(ev.due_date)
        job.due_date = new_due
        horizon = float(self.state.horizon)
        if job.initial_due_date >= horizon - 1e-9 or job.initial_due_date <= job.release_time + 1e-9:
            job.initial_due_date = new_due

    def _preempt_operation_on_machine(self, mid: str, t: float) -> None:
        """Preempt the operation currently processing on machine ``mid`` at time ``t``.

        If the machine has a schedule segment such that ``start < t < end``, we
        shorten that segment to end at ``t`` and return the remaining processing
        time of the corresponding operation back to the job. The job's
        ``current_op_index`` is set to this operation so that it can be
        rescheduled (possibly on another machine) with the remaining time.
        """

        mach = self.state.machines.get(mid)
        if mach is None:
            return

        seg_in_progress: Optional[ScheduleSegment] = None
        for seg in mach.schedule_segments:
            if seg.start < t < seg.end and seg.job_id:
                seg_in_progress = seg
                break
        if seg_in_progress is None:
            return

        job = self.state.jobs.get(seg_in_progress.job_id)
        if job is None:
            return

        was_completed = job.status == "completed"

        op: Optional[OperationState] = None
        for cand in job.ops:
            if cand.op_id == seg_in_progress.op_id:
                op = cand
                break
        if op is None:
            return

        old_pt = float(op.proc_time_realized)
        if old_pt <= 1e-9:
            return

        start = float(seg_in_progress.start)
        old_end = float(seg_in_progress.end)
        if not (start < t < old_end):
            return

        speed = max(1e-9, mach.speed)
        processed = max(0.0, min(old_pt, (t - start) * speed))
        remaining = old_pt - processed
        if remaining <= 1e-9:
            # Operation effectively finishes before or exactly at t.
            return

        # Shorten the machine segment to [start, t].
        seg_in_progress.end = t
        mach.busy_time += (t - old_end)
        mach.available_from = min(mach.available_from, t)

        if job.status == "cancelled":
            if mach.current_job_id == job.job_id and mach.current_op_id == op.op_id:
                mach.current_job_id = None
                mach.current_op_id = None
            return

        # Re-open this operation on the job so that the remaining part can be
        # scheduled again (same job/op index).
        k = int(op.index)
        job.current_op_index = k
        job.status = "waiting"
        job.next_available_time = float(t)

        # Remaining work content should include the unfinished part.
        job.remaining_work_content += remaining

        # Update operation state to reflect that it still needs processing.
        op.proc_time_realized = remaining
        op.status = "waiting"
        op.prev_start_time = op.start_time
        op.prev_machine_id = mach.machine_id
        op.start_time = None
        op.end_time = None
        op.rework_count += 1

        # If the job had been marked completed by this operation, undo that.
        if was_completed:
            job.status = "waiting"
            job.completion_time = None
            job.lateness = None
            job.tardiness = None

        # Clear current markers on the machine; actual availability is governed
        # by ``available_from`` and downtime blocks.
        if mach.current_job_id == job.job_id and mach.current_op_id == op.op_id:
            mach.current_job_id = None
            mach.current_op_id = None

        self._log_job_invariants("preempt_operation_on_machine")

    def _clear_future_segments_for_machine(self, mid: str, t: float) -> None:

        mach = self.state.machines.get(mid)
        if mach is None:
            return

        removed_by_job: Dict[str, List[str]] = {}
        kept_segments: List[ScheduleSegment] = []
        removed_busy = 0.0

        for seg in mach.schedule_segments:
            start_val = float(seg.start)
            if start_val >= t - 1e-9 and seg.job_id not in ("", "__DOWNTIME__"):
                removed_busy += max(0.0, float(seg.end) - start_val)
                jid = str(seg.job_id)
                removed_by_job.setdefault(jid, []).append(str(seg.op_id))
            else:
                kept_segments.append(seg)

        if removed_busy > 0.0:
            mach.schedule_segments = kept_segments
            mach.busy_time = max(0.0, mach.busy_time - removed_busy)
            if mach.schedule_segments:
                mach.available_from = max(float(s.end) for s in mach.schedule_segments)
            else:
                mach.available_from = min(mach.available_from, t)

        if not removed_by_job:
            return

        for jid, op_ids in removed_by_job.items():
            job = self.state.jobs.get(jid)
            if job is None or job.status == "cancelled":
                continue
            for op in job.ops:
                if str(op.op_id) in op_ids and op.status != "cancelled":
                    op.status = "waiting"
                    op.start_time = None
                    op.end_time = None

            k = 0
            while (
                k < job.total_ops
                and job.ops[k].status in ("done", "cancelled")
            ):
                k += 1
            job.current_op_index = k
            if k >= job.total_ops:
                job.status = "completed"
            else:
                job.status = "waiting"
                job.completion_time = None
                job.lateness = None
                job.tardiness = None
                job.next_available_time = max(job.next_available_time, t)

            job.total_work_content = sum(float(op.proc_time_realized) for op in job.ops)
            job.remaining_work_content = sum(
                float(op.proc_time_realized)
                for op in job.ops
                if op.status not in ("done", "cancelled")
            )

        self._log_job_invariants("clear_future_segments_for_machine")

    def _handle_breakdown(self, ev: BreakdownEvent, t: float) -> None:
        mid = str(ev.machine_id)
        dur = float(ev.duration)

        machines = self.state.machines
        groups = self.state.machine_groups

        mid_is_machine = mid in machines
        mid_is_group = mid in groups

        # If the same ID is used as both machine and group, issue a warning and prioritize interpreting it as machine,
        # to prevent a single event from accidentally affecting the entire group of machines.
        if mid_is_machine and mid_is_group:
            logger.warning(
                "BREAKDOWN event machine_id '%s' matches both a machine and a group; "
                "treating it as MACHINE-level only. Please avoid using identical ids "
                "for machines and groups.",
                mid,
            )

        # Determine which concrete machines are affected under strict semantics.
        affected_machines: List[str] = []
        if mid_is_machine:
            affected_machines.append(mid)
        elif mid_is_group:
            mg = groups.get(mid)
            if mg and isinstance(mg.get("machine_ids"), list):
                for m in mg["machine_ids"]:
                    m_id = str(m)
                    if m_id in machines:
                        affected_machines.append(m_id)

        if not affected_machines:
            logger.warning(f"BREAKDOWN for unknown machine_id/group: {mid}")
            return

        for real_mid in affected_machines:
            mach = self.state.machines.get(real_mid)
            if mach is None:
                continue

            # Baseline breakdown window for this machine.
            bd_start = t
            bd_end = t + dur

            # Preempt any in-progress work at time t and clear future
            # processing segments (but keep existing downtime segments).
            self._preempt_operation_on_machine(real_mid, t)
            self._clear_future_segments_for_machine(real_mid, t)

            # Collect all existing downtime segments that overlap with the
            # new breakdown window [bd_start, bd_end], and compute their
            # total length for correct downtime accounting.
            overlapping_downtimes: List[ScheduleSegment] = []
            kept_segments: List[ScheduleSegment] = []
            old_downtime_total = 0.0

            for seg in mach.schedule_segments:
                if seg.job_id == "__DOWNTIME__":
                    seg_start = float(seg.start)
                    seg_end = float(seg.end)
                    if seg_end > bd_start + 1e-9 and seg_start < bd_end - 1e-9:
                        overlapping_downtimes.append(seg)
                        old_downtime_total += max(0.0, seg_end - seg_start)
                        continue
                kept_segments.append(seg)

            if overlapping_downtimes:
                min_start = min([bd_start] + [float(s.start) for s in overlapping_downtimes])
                max_end = max([bd_end] + [float(s.end) for s in overlapping_downtimes])
                new_start = min_start
                new_end = max_end
                new_len = max(0.0, new_end - new_start)
                delta_downtime = max(0.0, new_len - old_downtime_total)
            else:
                new_start = bd_start
                new_end = bd_end
                new_len = max(0.0, new_end - new_start)
                delta_downtime = new_len

            # Update downtime statistics and machine status.
            if delta_downtime > 0.0:
                mach.downtime += delta_downtime
            mach.status = "down_breakdown"

            # Append the merged breakdown downtime segment and keep segments
            # sorted by time for determinism.
            kept_segments.append(
                ScheduleSegment(
                    start=new_start,
                    end=new_end,
                    job_id="__DOWNTIME__",
                    op_id="__DOWN_BD__",
                    is_frozen=False,
                )
            )
            kept_segments.sort(key=lambda s: (float(s.start), float(s.end)))
            mach.schedule_segments = kept_segments

            # Safety pass: ensure no processing segment overlaps with any
            # downtime window on this machine. If such overlap remains (for
            # example, due to a missed preemption in rare corner cases), we
            # truncate the processing segment to stop at the beginning of the
            # overlapping downtime, or drop it entirely if it lies fully
            # inside a downtime window.
            if mach.schedule_segments:
                downtime_windows: List[Tuple[float, float]] = []
                for seg in mach.schedule_segments:
                    if seg.job_id == "__DOWNTIME__":
                        ds = float(seg.start)
                        de = float(seg.end)
                        if de > ds + 1e-9:
                            downtime_windows.append((ds, de))

                if downtime_windows:
                    new_segments: List[ScheduleSegment] = []
                    removed_busy = 0.0

                    for seg in mach.schedule_segments:
                        if seg.job_id == "__DOWNTIME__":
                            new_segments.append(seg)
                            continue

                        s_start = float(seg.start)
                        s_end = float(seg.end)
                        keep_seg = True

                        for (ds, de) in downtime_windows:
                            if de <= s_start + 1e-9 or ds >= s_end - 1e-9:
                                continue

                            # Overlap exists. If the segment starts before the
                            # downtime, truncate it to [s_start, ds]; otherwise
                            # (segment entirely inside downtime or starting
                            # after ds), drop it.
                            if s_start + 1e-9 < ds:
                                new_end = min(ds, s_end)
                                if new_end > s_start + 1e-9:
                                    removed_busy += max(0.0, s_end - new_end)
                                    seg.end = new_end
                                    s_end = new_end
                                    # After truncation there is no further
                                    # overlap with any later downtime window
                                    # since ds are sorted in time order.
                                    break
                                else:
                                    removed_busy += max(0.0, s_end - s_start)
                                    keep_seg = False
                                    break
                            else:
                                removed_busy += max(0.0, s_end - s_start)
                                keep_seg = False
                                break

                        if keep_seg:
                            new_segments.append(seg)

                    if removed_busy > 0.0:
                        mach.schedule_segments = sorted(
                            new_segments, key=lambda s: (float(s.start), float(s.end))
                        )
                        mach.busy_time = max(0.0, mach.busy_time - removed_busy)
                        if mach.schedule_segments:
                            mach.available_from = max(
                                float(s.end) for s in mach.schedule_segments
                            )
                        else:
                            mach.available_from = min(mach.available_from, t)

            current_block = self._block_until_machine.get(real_mid, 0.0)
            self._block_until_machine[real_mid] = max(current_block, new_end)

    def _handle_repair_completion(self, ev: MachineRepairCompletionEvent, t: float) -> None:
        mid = str(ev.machine_id)
        group = self._infer_group_from_machine_id(mid)

        if mid in self._block_until_machine:
            self._block_until_machine[mid] = min(self._block_until_machine.get(mid, 0.0), t)
            if mid in self.state.machines:
                self.state.machines[mid].status = "idle"
        elif group is not None and group in self._block_until_group:
            self._block_until_group[group] = min(self._block_until_group.get(group, 0.0), t)
        else:
            # Unknown machine id / group for a repair completion event is
            # usually symptomatic of inconsistent events.jsonl (e.g., a
            # REPAIR_COMPLETION for a machine that never had a BREAKDOWN or
            # does not exist in the current model). We log a warning here so
            # that such ignored events are visible in runtime logs, matching
            # the behaviour of the offline strict checker.
            logger.warning(
                "REPAIR_COMPLETION for unknown machine_id={} (group={}); event will be ignored.",
                mid,
                group,
            )

    def _handle_ptime_change(self, ev: ProcessTimeChangeEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"PTIME_CHANGE for unknown job_id={ev.job_id}")
            return
        if job.status in ("cancelled", "completed"):
            logger.warning(
                "PTIME_CHANGE after {} for job_id={} at t={:.6f}; event will be ignored.",
                job.status,
                ev.job_id,
                t,
            )
            return
        idx = int(ev.step_index)
        if idx < 0 or idx >= len(job.ops):
            logger.warning(f"PTIME_CHANGE with invalid step_index={idx} for job_id={ev.job_id}")
            return
        op = job.ops[idx]
        # Frozen-zone semantics: if this operation is currently being processed
        # on any machine (there exists a scheduled segment with start < t < end),
        # we ignore the PTIME_CHANGE to avoid retroactive edits of in-flight work.
        for mach in self.state.machines.values():
            for seg in mach.schedule_segments:
                if seg.job_id != job.job_id or seg.op_id != op.op_id:
                    continue
                start = float(seg.start)
                end = float(seg.end)
                if start < t < end - 1e-9:
                    logger.info(
                        "Ignoring PTIME_CHANGE for job_id={} op_id={} at t={:.6f} "
                        "because the operation is currently processing in the frozen "
                        "zone [{:.6f}, {:.6f}] on machine {}.",
                        job.job_id,
                        op.op_id,
                        t,
                        start,
                        end,
                        mach.machine_id,
                    )
                    return
        old = op.proc_time_realized
        new = float(ev.new_process_time)
        op.proc_time_realized = new
        delta = new - old
        job.total_work_content += delta
        if idx >= job.current_op_index:
            job.remaining_work_content += delta

    def _handle_priority_change(self, ev: PriorityChangeEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"PRIORITY_CHANGE for unknown job_id={ev.job_id}")
            return
        if job.status in ("cancelled", "completed"):
            logger.warning(
                "PRIORITY_CHANGE after {} for job_id={} at t={:.6f}; event will be ignored.",
                job.status,
                ev.job_id,
                t,
            )
            return
        job.priority = float(ev.new_priority)

    def _handle_cancellation(self, ev: OrderCancellationEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"ORDER_CANCELLATION for unknown job_id={ev.job_id}")
            return
        if job.status == "cancelled":
            # Duplicate cancellation event; keep semantics idempotent but
            # surface it in logs for debugging.
            logger.warning(
                "Duplicate ORDER_CANCELLATION for job_id={} at t={:.6f}; event will be ignored.",
                ev.job_id,
                t,
            )
            return
        job.status = "cancelled"
        job.cancellation_time = float(t)
        # Mark remaining operations as cancelled
        for op in job.ops[job.current_op_index :]:
            op.status = "cancelled"
        # Remove any future schedule segments belonging to this job to avoid
        # phantom capacity blockage on machines. We keep historical segments
        # (seg.start < t) to preserve past Gantt information.
        for mach in self.state.machines.values():
            new_segments: List[ScheduleSegment] = []
            removed_busy = 0.0
            for seg in mach.schedule_segments:
                if seg.job_id == ev.job_id and float(seg.start) >= t - 1e-9:
                    removed_busy += max(0.0, float(seg.end) - float(seg.start))
                    continue
                new_segments.append(seg)
            if removed_busy > 0.0:
                mach.schedule_segments = new_segments
                mach.busy_time = max(0.0, mach.busy_time - removed_busy)
                if mach.schedule_segments:
                    mach.available_from = max(float(s.end) for s in mach.schedule_segments)
                else:
                    # No future work; if machine was only blocked by this
                    # cancelled job, allow it to become available at or before t.
                    mach.available_from = min(mach.available_from, t)
        # Remove from all machine queues
        for mach in self.state.machines.values():
            mach.queue = [q for q in mach.queue if q[0] != ev.job_id]
        # Record in Gantt for completeness
        self._gantt.append(
            {
                "job_id": ev.job_id,
                "operation": job.current_op_index,
                "machine_id": "",
                "start_time": float(t),
                "end_time": float(t),
                "status": "cancelled",
            }
        )

        job.current_op_index = job.total_ops
        job.total_work_content = sum(float(op.proc_time_realized) for op in job.ops)
        job.remaining_work_content = sum(
            float(op.proc_time_realized)
            for op in job.ops
            if getattr(op, "status", None) not in ("done", "cancelled")
        )

    def _handle_route_change(self, ev: RouteChangeEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"ROUTE_CHANGE for unknown job_id={ev.job_id}")
            return
        new_routing = list(ev.new_routing)
        new_ptimes = list(ev.new_process_times)
        from_step = int(ev.from_step or 0)
        k = max(from_step, job.current_op_index)

        # Preserve completed operations up to k
        preserved_ops = job.ops[:k]
        new_ops: List[OperationState] = []
        for i, (group, pt) in enumerate(zip(new_routing, new_ptimes)):
            idx = k + i
            op_id = f"{job.job_id}-op{idx}"
            pt_val = float(pt)
            new_ops.append(
                OperationState(
                    op_id=op_id,
                    job_id=job.job_id,
                    index=idx,
                    machine_group=group,
                    candidate_machines=self._candidate_machines_for_group(group),
                    proc_time_nominal=pt_val,
                    proc_time_realized=pt_val,
                    status="not_released",
                )
            )
        job.ops = preserved_ops + new_ops
        job.total_ops = len(job.ops)

        # Recompute work contents
        job.total_work_content = sum(op.proc_time_realized for op in job.ops)
        job.remaining_work_content = sum(
            op.proc_time_realized for op in job.ops[job.current_op_index :]
        )

        self._log_job_invariants("route_change")

    def _handle_due_date_change(self, ev: DueDateChangeEvent, t: float) -> None:
        job = self.state.jobs.get(ev.job_id)
        if not job:
            logger.warning(f"DUE_DATE_CHANGE for unknown job_id={ev.job_id}")
            return
        if job.status in ("cancelled", "completed"):
            logger.warning(
                "DUE_DATE_CHANGE after {} for job_id={} at t={:.6f}; event will be ignored.",
                job.status,
                ev.job_id,
                t,
            )
            return
        job.due_date = float(ev.new_due_date)
        # Keep initial_due_date unchanged to measure relaxation/tightening

    def _handle_pm(self, ev: PreventiveMaintenanceEvent, t: float) -> None:
        mid = str(ev.machine_id)
        dur = float(ev.duration)

        machines = self.state.machines
        groups = self.state.machine_groups

        mid_is_machine = mid in machines
        mid_is_group = mid in groups

        if mid_is_machine and mid_is_group:
            logger.warning(
                "PREVENTIVE_MAINTENANCE event machine_id '%s' matches both a machine and a group; "
                "treating it as MACHINE-level only. Please avoid using identical ids "
                "for machines and groups.",
                mid,
            )

        # Determine which concrete machines are affected under strict semantics.
        affected_machines: List[str] = []
        if mid_is_machine:
            affected_machines.append(mid)
        elif mid_is_group:
            mg = groups.get(mid)
            if mg and isinstance(mg.get("machine_ids"), list):
                for m in mg["machine_ids"]:
                    m_id = str(m)
                    if m_id in machines:
                        affected_machines.append(m_id)

        if not affected_machines:
            logger.warning(f"PREVENTIVE_MAINTENANCE for unknown machine_id/group: {mid}")
            return

        for real_mid in affected_machines:
            mach = self.state.machines.get(real_mid)
            if mach is None:
                continue

            # Baseline PM start: not before current time nor before all work
            # already scheduled on this machine.
            down_start = max(t, mach.available_from)

            # If there is an operation in progress at time t, we start PM only
            # after that operation finishes (non-preemptive behavior).
            seg_in_progress: Optional[ScheduleSegment] = None
            for seg in mach.schedule_segments:
                if seg.start < t < seg.end and seg.job_id:
                    seg_in_progress = seg
                    break
            if seg_in_progress is not None:
                down_start = max(down_start, float(seg_in_progress.end))

            down_end = down_start + dur

            has_overlapping_downtime = False
            for seg in mach.schedule_segments:
                if seg.job_id == "__DOWNTIME__":
                    seg_start = float(seg.start)
                    seg_end = float(seg.end)
                    if seg_end > down_start + 1e-9 and seg_start < down_end - 1e-9:
                        has_overlapping_downtime = True
                        break

            if has_overlapping_downtime:
                # This PM window lies fully inside or overlaps an existing
                # downtime interval on the same machine, so applying it would
                # not change the effective behaviour. We treat it as a
                # no-op but log a warning so that ignored events are visible
                # during debugging of generated scenarios.
                logger.warning(
                    "PREVENTIVE_MAINTENANCE for machine_id={} at t={:.6f} overlaps existing downtime; event will be ignored.",
                    real_mid,
                    t,
                )
                continue

            current_block = self._block_until_machine.get(real_mid, 0.0)
            self._block_until_machine[real_mid] = max(current_block, down_end)
            mach.downtime += dur

            self._clear_future_segments_for_machine(real_mid, down_start)

            # If the current simulation time lies inside the PM window, mark
            # the machine as down for preventive maintenance.
            if self.state.time >= down_start and self.state.time < down_end:
                mach.status = "down_pm"

            # Record an explicit downtime segment for visualization.
            mach.schedule_segments.append(
                ScheduleSegment(
                    start=down_start,
                    end=down_end,
                    job_id="__DOWNTIME__",
                    op_id="__DOWN_PM__",
                    is_frozen=False,
                )
            )

    def _infer_group_from_machine_id(self, mid: str) -> Optional[str]:
        # 1) Direct mapping from machines
        mid_str = str(mid)
        if mid_str in self.state.machines:
            return self.state.machines[mid_str].group
        # 2) If mid is exactly a known group id
        if mid_str in self.state.machine_groups:
            return mid_str
        # 2b) Composite ids such as "G1-M1" or "GroupA-M1": try to map the left part to a group
        if "-" in mid_str and self.state.machine_groups:
            left, _ = mid_str.split("-", 1)
            if left in self.state.machine_groups:
                return left
            m_g = re.match(r"^[Gg](\d+)$", left)
            if m_g:
                idx0 = int(m_g.group(1)) - 1
                if idx0 >= 0:
                    groups_sorted = sorted(self.state.machine_groups.keys())
                    if groups_sorted:
                        idx = idx0 % len(groups_sorted)
                        return groups_sorted[idx]
        # 3) Heuristic: M1, M2, ... mapped round‑robin to known groups
        m = re.match(r"^[Mm](\d+)$", mid_str)
        if m and self.state.machine_groups:
            idx = (int(m.group(1)) - 1) % len(self.state.machine_groups)
            return list(sorted(self.state.machine_groups.keys()))[idx]
        return None

    # ------------------------------------------------------------------
    # Ready operations and observation helpers
    # ------------------------------------------------------------------
    def _get_ready_operations(self) -> List[OperationState]:
        ready: List[OperationState] = []
        t = self.state.time
        eps = 1e-9

        for job in self.state.jobs.values():
            if job.status in ("completed", "cancelled"):
                continue

            k = int(getattr(job, "current_op_index", 0))
            if k < 0:
                k = 0

            ops = getattr(job, "ops", [])
            while (
                k < job.total_ops
                and k < len(ops)
                and getattr(ops[k], "status", None) in ("done", "cancelled")
            ):
                k += 1
            if k != job.current_op_index:
                job.current_op_index = k

            if k >= job.total_ops:
                continue

            if job.release_time > t:
                continue
            if job.next_available_time > t:
                continue

            if k >= len(ops):
                continue

            op = ops[k]
            if getattr(op, "status", None) in ("cancelled", "done"):
                continue

            candidates = list(getattr(op, "candidate_machines", []))
            if not candidates:
                continue

            try:
                job_avail = max(float(job.release_time), float(job.next_available_time))
            except Exception:
                job_avail = float(getattr(job, "next_available_time", t))

            can_start_now = False
            for mid in candidates:
                mach = self.state.machines.get(mid)
                if mach is None:
                    continue

                block_until = float(self._machine_block_until(mid, mach.group))
                try:
                    m_avail = float(mach.available_from)
                except Exception:
                    m_avail = t

                start = max(t, job_avail, m_avail, block_until)
                if start <= t + eps:
                    can_start_now = True
                    break

            if not can_start_now:
                continue

            ready.append(op)

        return ready

    # ------------------------------------------------------------------
    # Snapshot export
    # ------------------------------------------------------------------
    def export_snapshot(self) -> Snapshot:
        """Build a rich Snapshot object from the current SystemState."""

        s = self.state
        t = s.time

        # Jobs
        job_snaps: List[JobSnapshot] = []
        for job in s.jobs.values():
            op_snaps: List[JobOpSnapshot] = []
            for op in job.ops:
                # Remaining time is defined relative to current decision time
                if op.start_time is None:
                    remaining = op.proc_time_realized
                else:
                    remaining = max(0.0, op.proc_time_realized - max(0.0, t - op.start_time))
                op_snaps.append(
                    JobOpSnapshot(
                        op_id=op.op_id,
                        job_id=op.job_id,
                        index=op.index,
                        machine_group=op.machine_group,
                        candidate_machines=list(op.candidate_machines),
                        proc_time_nominal=op.proc_time_nominal,
                        proc_time_realized=op.proc_time_realized,
                        status=op.status,
                        start_time=op.start_time,
                        end_time=op.end_time,
                        remaining_time=remaining,
                        prev_start_time=op.prev_start_time,
                        prev_machine_id=op.prev_machine_id,
                        rework_count=op.rework_count,
                    )
                )
            job_snaps.append(
                JobSnapshot(
                    job_id=job.job_id,
                    family=job.family,
                    release_time=job.release_time,
                    due_date=job.due_date,
                    initial_due_date=job.initial_due_date,
                    priority=job.priority,
                    weight=job.weight,
                    status=job.status,
                    current_op_index=job.current_op_index,
                    total_ops=job.total_ops,
                    total_work_content=job.total_work_content,
                    remaining_work_content=job.remaining_work_content,
                    completion_time=job.completion_time,
                    lateness=job.lateness,
                    tardiness=job.tardiness,
                    cancellation_time=job.cancellation_time,
                    ops=op_snaps,
                )
            )

        # Machines
        machine_snaps: List[MachineSnapshot] = []
        for mach in s.machines.values():
            queue_view: List[Dict[str, float]] = []
            for job_id, op_id, pr, dd, at in mach.queue:
                queue_view.append(
                    {
                        "job_id": job_id,
                        "op_id": op_id,
                        "priority": float(pr),
                        "due_date": float(dd),
                        "arrival_to_queue_time": float(at),
                    }
                )
            seg_snaps = [
                MachineScheduleSegmentSnapshot(
                    start=seg.start,
                    end=seg.end,
                    job_id=seg.job_id,
                    op_id=seg.op_id,
                    is_frozen=seg.is_frozen,
                )
                for seg in mach.schedule_segments
            ]
            machine_snaps.append(
                MachineSnapshot(
                    machine_id=mach.machine_id,
                    group=mach.group,
                    speed=mach.speed,
                    status=mach.status,
                    available_from=mach.available_from,
                    current_job_id=mach.current_job_id,
                    current_op_id=mach.current_op_id,
                    queue=queue_view,
                    schedule_segments=seg_snaps,
                )
            )

        # Pending events
        pending: List[EventSnapshot] = []
        for idx in range(self._event_index, len(self._events)):
            ev = self._events[idx]
            payload = ev.model_dump(exclude={"time", "event_type"})
            pending.append(
                EventSnapshot(
                    time=float(ev.time),
                    event_type=str(ev.event_type),
                    payload=payload,
                )
            )

        # System stats
        num_jobs_total = len(s.jobs)
        num_jobs_arrived = sum(1 for j in s.jobs.values() if j.release_time <= t)
        num_jobs_completed = sum(1 for j in s.jobs.values() if j.status == "completed")
        num_jobs_cancelled = sum(1 for j in s.jobs.values() if j.status == "cancelled")
        wip_count = sum(
            1 for j in s.jobs.values() if j.status in ("waiting", "processing", "not_arrived")
        )

        queue_length_by_machine: Dict[str, int] = {
            mach.machine_id: len(mach.queue) for mach in s.machines.values()
        }
        queue_length_by_group: Dict[str, int] = {}
        for mach in s.machines.values():
            queue_length_by_group.setdefault(mach.group, 0)
            queue_length_by_group[mach.group] += len(mach.queue)

        utilization_by_machine: Dict[str, float] = {}
        for mach in s.machines.values():
            if t > 0:
                utilization_by_machine[mach.machine_id] = mach.busy_time / t
            else:
                utilization_by_machine[mach.machine_id] = 0.0

        utilization_by_group: Dict[str, float] = {}
        # Aggregate busy time per group
        busy_by_group: Dict[str, float] = defaultdict(float)
        for mach in s.machines.values():
            busy_by_group[mach.group] += mach.busy_time
        for group, busy in busy_by_group.items():
            utilization_by_group[group] = busy / t if t > 0 else 0.0

        system_stats = SystemStats(
            num_jobs_total=num_jobs_total,
            num_jobs_arrived=num_jobs_arrived,
            num_jobs_completed=num_jobs_completed,
            num_jobs_cancelled=num_jobs_cancelled,
            wip_count=wip_count,
            queue_length_by_machine=queue_length_by_machine,
            queue_length_by_group=queue_length_by_group,
            utilization_by_machine=utilization_by_machine,
            utilization_by_group=utilization_by_group,
            num_reschedules=s.num_reschedules,
            last_schedule_change_time=s.last_schedule_change_time,
            event_counters=dict(self._event_counters),
        )

        stability_stats = self._compute_stability_stats(self._prev_snapshot, job_snaps)

        snap = Snapshot(
            time=t,
            prev_decision_time=s.prev_decision_time,
            horizon=s.horizon,
            lookahead_horizon=s.lookahead_horizon,
            scenario_id=getattr(self.model.meta, "run_name", None),
            seed=self.model.meta.seed,
            config_hash=None,
            plant=self.model.plant.model_dump(),
            scale=self.model.scale.model_dump(),
            targets=self.model.targets.model_dump(),
            dynamics=self.model.dynamics.model_dump(),
            dynamic_scenarios=self.model.dynamic_scenarios.model_dump(),
            jobs=job_snaps,
            machines=machine_snaps,
            pending_events=pending,
            system_stats=system_stats,
            stability_stats=stability_stats,
        )
        return snap

    def _compute_stability_stats(
        self,
        prev_snapshot: Optional[Snapshot],
        current_jobs: List[JobSnapshot],
    ) -> StabilityStats:
        if prev_snapshot is None:
            return StabilityStats(
                changed_ops_ratio=0.0,
                avg_start_time_shift=0.0,
                max_start_time_shift=0.0,
            )

        prev_map: Dict[Tuple[str, int], Optional[float]] = {}
        for j in prev_snapshot.jobs:
            for op in j.ops:
                prev_map[(op.job_id, op.index)] = op.start_time

        diffs: List[float] = []
        changed_count = 0
        total_count = 0
        for j in current_jobs:
            for op in j.ops:
                key = (op.job_id, op.index)
                if key not in prev_map:
                    continue
                total_count += 1
                prev_start = prev_map[key]
                curr_start = op.start_time
                if prev_start is None or curr_start is None:
                    continue
                dt = abs(curr_start - prev_start)
                if dt > 1e-9:
                    changed_count += 1
                    diffs.append(dt)

        if not diffs or total_count == 0:
            return StabilityStats(
                changed_ops_ratio=0.0,
                avg_start_time_shift=0.0,
                max_start_time_shift=0.0,
            )

        return StabilityStats(
            changed_ops_ratio=changed_count / max(1, total_count),
            avg_start_time_shift=sum(diffs) / len(diffs),
            max_start_time_shift=max(diffs),
        )

    # ------------------------------------------------------------------
    # Convenience accessors
    # ------------------------------------------------------------------
    def get_ready_operations(self) -> List[OperationState]:
        """Return a shallow copy of the current ready-operations list.

        Downstream components (e.g. environments, agents) should prefer this
        method over the internal :meth:`_get_ready_operations` helper.
        """

        return list(self._get_ready_operations())

    def get_action_timing(self, action: Dict[str, Any]) -> Optional[Dict[str, float]]:
        """Return an estimated timing profile for ``action`` under the current state.

        The result is computed using the same instantaneous semantics as
        :meth:`estimate_action_score`, but instead of a scalar score it
        returns a dictionary with:

        - ``job_id``: job identifier (str)
        - ``op_index``: index of the operation being scheduled (int)
        - ``machine_id``: selected concrete machine id (str)
        - ``start_time``: earliest feasible start time given all constraints
        - ``end_time``: corresponding end time on the selected machine
        - ``proc_time_raw``: realized processing time before speed adjustment
        - ``machine_speed``: speed of the selected machine
        - ``proc_time_effective``: actual processing time on the machine

        The simulation state is not mutated.
        """

        try:
            job_id = str(action["job_id"])  # type: ignore[index]
            group = str(action.get("machine_group"))
            requested_mid = action.get("machine_id")
        except Exception:
            return None

        job = self.state.jobs.get(job_id)
        if job is None or job.current_op_index >= job.total_ops:
            return None

        k = job.current_op_index
        op = job.ops[k]

        machine_id = self._select_machine_for_action(job_id, group, requested_mid)
        mach = self.state.machines.get(machine_id)
        if mach is None:
            return None

        t_now = self.state.time
        job_avail = max(job.release_time, job.next_available_time)
        block_until = self._machine_block_until(machine_id, mach.group)
        start = max(t_now, job_avail, mach.available_from, block_until)

        # Mirror the non-overlap safeguard used in ``step_action`` so that
        # timing diagnostics are consistent with the actual scheduling
        # semantics: a new segment can never start before the latest
        # existing segment on the same machine.
        if mach.schedule_segments:
            latest_end = max(float(seg.end) for seg in mach.schedule_segments)
            if start < latest_end - 1e-9:
                start = latest_end

        raw_pt = float(op.proc_time_realized)
        speed = float(getattr(mach, "speed", 1.0))
        eff_pt = raw_pt / max(1e-9, speed)
        end = start + eff_pt

        return {
            "job_id": job_id,
            "op_index": float(k),
            "machine_id": machine_id,
            "start_time": float(start),
            "end_time": float(end),
            "proc_time_raw": float(raw_pt),
            "machine_speed": float(speed),
            "proc_time_effective": float(eff_pt),
        }

    def get_gantt(self) -> List[Dict[str, Any]]:
        """Return an immutable copy of the internal Gantt list."""

        return list(self._gantt)

    def get_events(self) -> List[Event]:
        """Return the underlying event list (useful for debugging/vis)."""

        return list(self._events)
